name: fababean-gbs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - seaborn
  - matplotlib
  - biopython
  - networkx
  - openpyxl
  - plink=1.90b6.26
  - plink2
  - admixture
  - iqtree
  - fasttree
  - bcftools
  - vcftools
  - r-base>=4.3
  - r-ggplot2
  - r-dplyr
  - r-gridextra
